name: HostGrap Remote Support Filename Method

on:
  workflow_dispatch:

jobs:
  build-filename:
    runs-on: ubuntu-latest
    steps:
      - name: Download Official RustDesk Client
        run: |
          wget https://github.com/rustdesk/rustdesk/releases/download/1.4.8/rustdesk-1.4.8-x86_64.exe -O rustdesk.exe

      - name: Rename with HostGrap Server Settings
        run: |
          # RustDesk එකේ නම ඇතුළට host, key සහ api සේරම Format එකකට දානවා
          # Format: rustdesk-host=<host>-key=<key>.exe
          SERVER_HOST="remotedesk.hglk.link"
          SERVER_KEY="LyAnbMUs2DAvCngHCVn8rIXXr48L8bBlSK8xgypAzek="
          
          NEW_NAME="HostGrap-Support-host=${SERVER_HOST},key=${SERVER_KEY}.exe"
          mv rustdesk.exe "$NEW_NAME"

      - name: Upload HostGrap Application
        uses: actions/upload-artifact@v4
        with:
          name: HostGrap-Support-EXE
          path: "*.exe"
